### ISSUE TITLE
query with pull doesn't work without ?table

### ISSUE THREAD

**Issue by stevebuik** [ribelo/doxa#6]
I can use this very nice feature of Datomic and Doxa https://github.com/ribelo/doxa/blob/master/test/ribelo/doxa_test.cljc#L435

but if I can't figure out how to use it without using the ?table binding. Is this possible?

If so, can you add a test or docs to illustrate it?

**Comment by ribelo** [comment]
keep wondering if `?table` is needed. It might make `doxa` faster than `datascript` because it allows to limit the iterated elements, but it wrecks full compatibility with `datascript` or `datomic`.

I can make that, `pull` can takes a single key as an argument, but then there is no guarantee that it will return the right value. Uniqueness is watched after [?table ?eid], the `?eid` itself can occur multiple times, for example `[:user/settings :ivan]` and `[:user/orders :ivan]`, then the first result encountered would be returned. I am not in favour of this solution.

**Comment by stevebuik** [comment]
ok. I don't mind being forced to use ?table for this since I know which entity I am pulling. 

I'm ok if you want to pause this one.

I like the idea of having ?table for queries for performance, at least until you find another way to beat datascript :)

IMHO using datalog should not be expected to be super fast. If speed is the requirement in a re-frame app, then both the pull and query api should not be used. Instead a get-in directly from the app-db will be best because then re-frame can use identical? in layer 2 subs. For me, this is the better answer when read performance is the goal. 

Maybe the docs can say:

dx/q = slowest (use with care)
dx/pull = much faster. use if you can
get-in = fastest. use for high performance requirements

That's good enough for me. And I'm sure you will learn some new tricks to make query faster.

**Comment by stevebuik** [comment]
My workaround for this is to use dx/q to find the entities using the fast ?table feature and then to map dx/pull over the idents. 

I'm curious, is this similar to how dx/q implements pull internally? i.e. is the perf going to be similar (but faster because of ?table)

This workaround has the added benefit of being able to use a transducer for post-pull transforms so a perf gain there as well.

**Comment by ribelo** [comment]
Probably done. Please check.

**Comment by stevebuik** [comment]
?table support removed
